apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - daemonset.yaml
  - monitor.yaml
  - rules.yaml
images:
  - name: ghcr.io/dafnifacility/flatcar-linux-ue-exporter
    newTag: v0.2.0
