apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ue-monitor
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: http-prom
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
  selector:
    matchLabels:
      app: flatcar-linux-ue-exporter